#!/usr/bin/env python3
"""Example 2 — Hamiltonian simulation, two independent ways.

Compute exp(-i H t)|psi> with two different primitives and check both
against dense linear algebra:

  * QSVT  -- block-encode H, apply a polynomial approximation of exp(-ixt)
             built from Jacobi-Anger phase factors (generated by QSPPACK).
  * Trotter -- a product formula, no block encoding or ancillas, with the
               error-vs-steps trade-off and a resource estimate.

Because the two constructions are completely different, agreeing with the
same dense reference means they cross-validate each other. This is the
"primitives compose into applications" story made concrete.

Prerequisite: qsppack (installed with the wheel). Run: python3 02_hamiltonian_simulation.py
"""

from __future__ import annotations

import os

import cudaq
import numpy as np
from scipy.linalg import expm

from cudaq_algorithms import (PauliLCU, PhaseSequence, QSVT, Trotter,
                              recover_real_time_evolution)
from cudaq_algorithms import sim_utils as sim

_PAULIS = {
    "I": np.eye(2, dtype=complex),
    "X": np.array([[0, 1], [1, 0]], dtype=complex),
    "Z": np.diag([1.0, -1.0]).astype(complex),
}


def dense(terms, num_qubits):
    # Little-endian, matching CUDA-Q: word[i] acts on qubit i, and qubit 0
    # is the least-significant bit, so build P[word[0]] as the rightmost
    # tensor factor by kron-ing each successive Pauli on the left.
    matrix = np.zeros((1 << num_qubits, 1 << num_qubits), dtype=complex)
    for word, coefficient in terms.items():
        factor = np.array([[1]], dtype=complex)
        for label in word:
            factor = np.kron(_PAULIS[label], factor)
        matrix = matrix + coefficient * factor
    return matrix


def jacobi_anger_phases(tau, degree):
    """cos/sin QSP phases for exp(-i tau x) via Jacobi-Anger + QSPPACK."""
    import contextlib
    import io

    import qsppack
    from scipy import special

    cos_coeffs = np.array([0.5 * special.jv(0, tau)] +
                          [((-1)**k) * special.jv(2 * k, tau)
                           for k in range(1, degree // 2 + 1)])
    sin_coeffs = np.array([((-1)**k) * special.jv(2 * k + 1, tau)
                           for k in range(degree // 2)])
    options = {
        "criteria": 1e-12,
        "method": "Newton",
        "typePhi": "full",
        "useReal": True
    }
    with contextlib.redirect_stdout(io.StringIO()):  # hush the QSP solver
        cos_phases, _ = qsppack.solve(cos_coeffs, 0, {
            **options, "targetPre": True
        })
        sin_phases, _ = qsppack.solve(sin_coeffs, 1, {
            **options, "targetPre": False
        })
    return [float(p) for p in cos_phases], [float(p) for p in sin_phases]


def main() -> int:
    cudaq.set_target(os.environ.get("CUDAQ_DEFAULT_SIMULATOR", "qpp-cpu"))

    terms = {"ZZ": 0.7, "XI": 0.4, "IX": 0.4, "ZI": 0.31}
    num_qubits = 2
    time = 0.8
    matrix = dense(terms, num_qubits)

    rng = np.random.default_rng(1)
    psi = rng.normal(size=1 << num_qubits).astype(np.complex128)
    psi /= np.linalg.norm(psi)
    exact = expm(-1j * matrix * time) @ psi

    # -- QSVT --------------------------------------------------------------
    encoding = PauliLCU(terms)
    transformer = QSVT(encoding)
    tau = encoding.alpha * time
    cos_phases, sin_phases = jacobi_anger_phases(tau, degree=16)
    cos_state = sim.transform(transformer, psi,
                              PhaseSequence(cos_phases, convention="qsp"))
    sin_state = sim.transform(transformer, psi,
                              PhaseSequence(sin_phases, convention="qsp"))
    qsvt_state = recover_real_time_evolution(cos_state, sin_state, cos_phases,
                                             sin_phases)
    qsvt_error = float(np.max(np.abs(qsvt_state - exact)))
    print(f"QSVT   (degree 16) : max amplitude error {qsvt_error:.2e}")

    # -- Trotter -----------------------------------------------------------
    evolution = Trotter(terms)
    print("Trotter (order 2)  : error shrinks as steps^-2")
    for steps in (1, 2, 4, 8, 16):
        trotter_state = sim.evolve(evolution, psi, time, steps=steps, order=2)
        error = float(np.max(np.abs(trotter_state - exact)))
        print(f"     steps={steps:2d}   max amplitude error {error:.2e}")
    resources = evolution.resources(steps=16, order=2)
    print(f"   resource estimate at 16 steps: "
          f"{resources.pauli_rotations} Pauli rotations")

    assert qsvt_error < 1e-6
    print("\nOK — two different circuits, one physics: both reproduce "
          "exp(-iHt)|psi>.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
